// Coral Island Database — Game Data
window.GameData = {

  crops: [
    { id:  1, name: 'Strawberry',    type: 'Fruit',     season: 'spring', rank: 'A', growTime:  8, sellPrice: 120, regrows: true  },
    { id:  2, name: 'Tulip',         type: 'Flower',    season: 'spring', rank: 'E', growTime:  6, sellPrice:  25, regrows: false },
    { id:  3, name: 'Cauliflower',   type: 'Vegetable', season: 'spring', rank: 'B', growTime: 12, sellPrice:  90, regrows: false },
    { id:  4, name: 'Potato',        type: 'Vegetable', season: 'spring', rank: 'D', growTime:  6, sellPrice:  30, regrows: false },
    { id:  5, name: 'Parsnip',       type: 'Vegetable', season: 'spring', rank: 'F', growTime:  4, sellPrice:  20, regrows: false },
    { id:  6, name: 'Blueberry',     type: 'Fruit',     season: 'summer', rank: 'B', growTime: 14, sellPrice:  80, regrows: true  },
    { id:  7, name: 'Tomato',        type: 'Vegetable', season: 'summer', rank: 'C', growTime:  7, sellPrice:  35, regrows: true  },
    { id:  8, name: 'Corn',          type: 'Grain',     season: 'summer', rank: 'E', growTime: 14, sellPrice:  40, regrows: true  },
    { id:  9, name: 'Sunflower',     type: 'Flower',    season: 'summer', rank: 'D', growTime:  8, sellPrice:  45, regrows: false },
    { id: 10, name: 'Hot Pepper',    type: 'Vegetable', season: 'summer', rank: 'C', growTime:  5, sellPrice:  40, regrows: true  },
    { id: 11, name: 'Pumpkin',       type: 'Vegetable', season: 'fall',   rank: 'D', growTime: 13, sellPrice:  55, regrows: false },
    { id: 12, name: 'Eggplant',      type: 'Vegetable', season: 'fall',   rank: 'C', growTime:  5, sellPrice:  30, regrows: true  },
    { id: 13, name: 'Cranberry',     type: 'Fruit',     season: 'fall',   rank: 'A', growTime:  7, sellPrice: 130, regrows: true  },
    { id: 14, name: 'Wheat',         type: 'Grain',     season: 'fall',   rank: 'F', growTime:  4, sellPrice:  25, regrows: false },
    { id: 15, name: 'Yam',           type: 'Vegetable', season: 'fall',   rank: 'D', growTime:  8, sellPrice:  50, regrows: false },
    { id: 16, name: 'Crystal Berry', type: 'Fruit',     season: 'winter', rank: 'B', growTime: 16, sellPrice: 110, regrows: false },
    { id: 17, name: 'Snow Pea',      type: 'Vegetable', season: 'winter', rank: 'C', growTime:  6, sellPrice:  40, regrows: true  },
    { id: 18, name: 'Frost Lily',    type: 'Flower',    season: 'winter', rank: 'E', growTime:  7, sellPrice:  30, regrows: false },
    { id: 19, name: 'Ice Beet',      type: 'Vegetable', season: 'winter', rank: 'D', growTime: 10, sellPrice:  60, regrows: false },
  ],

  caves: [
    { id:  1, name: 'Copper Ore',      type: 'Mineral',  mine: 'earth',    floors: '1–10'  },
    { id:  2, name: 'Coal',            type: 'Mineral',  mine: 'earth',    floors: '5–15'  },
    { id:  3, name: 'Iron Ore',        type: 'Mineral',  mine: 'earth',    floors: '11–20' },
    { id:  4, name: 'Silver Ore',      type: 'Mineral',  mine: 'earth',    floors: '16–25' },
    { id:  5, name: 'Amethyst',        type: 'Gem',      mine: 'earth',    floors: '21–30' },
    { id:  6, name: 'Gold Ore',        type: 'Mineral',  mine: 'earth',    floors: '26–40' },
    { id:  7, name: 'Coral Fragment',  type: 'Material', mine: 'water',    floors: '1–15'  },
    { id:  8, name: 'Sea Crystal',     type: 'Gem',      mine: 'water',    floors: '16–25' },
    { id:  9, name: 'Pearl',           type: 'Gem',      mine: 'water',    floors: '26–40' },
    { id: 10, name: 'Storm Stone',     type: 'Mineral',  mine: 'wind',     floors: '1–15'  },
    { id: 11, name: 'Emerald Shard',   type: 'Gem',      mine: 'wind',     floors: '10–25' },
    { id: 12, name: 'Sky Crystal',     type: 'Gem',      mine: 'wind',     floors: '20–40' },
    { id: 13, name: 'Fire Ruby',       type: 'Gem',      mine: 'fire',     floors: '1–15'  },
    { id: 14, name: 'Obsidian',        type: 'Mineral',  mine: 'fire',     floors: '10–25' },
    { id: 15, name: 'Dragon Shard',    type: 'Gem',      mine: 'fire',     floors: '25–40' },
    { id: 16, name: 'Memory Fragment', type: 'Artifact', mine: 'memories', floors: '1–20'  },
    { id: 17, name: 'Ancient Relic',   type: 'Artifact', mine: 'memories', floors: '10–30' },
    { id: 18, name: 'Lost Echo',       type: 'Artifact', mine: 'memories', floors: '25–40' },
  ],

  foraging: [
    { id:  1, name: 'Wild Berries',     season: 'spring', location: 'Forest Trail',    area: 'Forest'  },
    { id:  2, name: 'Fiddlehead Fern',  season: 'spring', location: 'River Bank',      area: 'Forest'  },
    { id:  3, name: 'Spring Onion',     season: 'spring', location: 'Hilltop Fields',  area: 'Plains'  },
    { id:  4, name: 'Daffodil',         season: 'spring', location: 'Meadow Path',     area: 'Plains'  },
    { id:  5, name: 'Coconut',          season: 'summer', location: 'Tropical Grove',  area: 'Coastal' },
    { id:  6, name: 'Palm Fruit',       season: 'summer', location: 'Coastal Path',    area: 'Coastal' },
    { id:  7, name: 'Sea Urchin',       season: 'summer', location: 'Tide Pools',      area: 'Beach'   },
    { id:  8, name: 'Seaweed',          season: 'all',    location: 'Shoreline',        area: 'Beach'   },
    { id:  9, name: 'Wild Mushroom',    season: 'fall',   location: 'Deep Forest',     area: 'Forest'  },
    { id: 10, name: 'Chanterelle',      season: 'fall',   location: 'Forest Trail',    area: 'Forest'  },
    { id: 11, name: 'Crab Apple',       season: 'fall',   location: 'Orchard Edge',    area: 'Plains'  },
    { id: 12, name: 'Hazelnut',         season: 'fall',   location: 'Forest Path',     area: 'Forest'  },
    { id: 13, name: 'Holly Berry',      season: 'winter', location: 'Snow Fields',     area: 'Plains'  },
    { id: 14, name: 'Ice Crystal',      season: 'winter', location: 'Frozen Lake',     area: 'Lake'    },
    { id: 15, name: 'Winter Root',      season: 'winter', location: 'Snowy Plains',    area: 'Plains'  },
  ],

  npcs: [
    {
      id: 1, name: 'Sam',   initials: 'SA', role: 'Fisherman',       location: 'Harbor',
      schedule: 'Harbor 8am–5pm · Tavern evenings',
      lovedGifts: ['Fresh Tuna', 'Coffee', 'Sea Bass'],
      quest: 'Requests rare deep-sea fish for his collection. Reward: Fishing Rod upgrade.',
      color: '#0369a1',
    },
    {
      id: 2, name: 'Lily',  initials: 'LI', role: 'Botanist',        location: 'Greenhouse',
      schedule: 'Greenhouse 7am–4pm · Park afternoons',
      lovedGifts: ['Rare Flowers', 'Honey', 'Crystal Berry'],
      quest: 'Seeking exotic plant specimens for her greenhouse research. Reward: Rare seed packets.',
      color: '#15803d',
    },
    {
      id: 3, name: 'Marcus', initials: 'MA', role: 'Chef',           location: 'The Reef Restaurant',
      schedule: 'Restaurant 10am–10pm · Market mornings',
      lovedGifts: ['Truffle', 'Cranberry', 'Pumpkin'],
      quest: 'Needs signature ingredients for a new island dish. Reward: Cooking recipes.',
      color: '#b45309',
    },
    {
      id: 4, name: 'Elena', initials: 'EL', role: 'Doctor',          location: 'Island Clinic',
      schedule: 'Clinic 9am–6pm · Beach evenings',
      lovedGifts: ['Medicinal Herbs', 'Sea Crystal', 'Amethyst'],
      quest: 'Researching island flora for new remedies. Reward: Stamina boost recipe.',
      color: '#9333ea',
    },
    {
      id: 5, name: 'Tidal', initials: 'TI', role: 'Marine Biologist', location: 'Research Center',
      schedule: 'Research Center 8am–6pm · Reef afternoons',
      lovedGifts: ['Sea Crystal', 'Coral Fragment', 'Pearl'],
      quest: 'Documenting coral reef restoration progress. Completion unlocks the Water Mine.',
      color: '#0f766e',
    },
    {
      id: 6, name: 'Naomi', initials: 'NA', role: 'Mayor',           location: 'Town Hall',
      schedule: 'Town Hall 9am–5pm · Village patrol evenings',
      lovedGifts: ['Gold Ore', 'Ancient Relic', 'Cranberry'],
      quest: "Restore the island's Town Rank. Central to all rank upgrade quests.",
      color: '#dc2626',
    },
    {
      id: 7, name: 'Keanu', initials: 'KE', role: 'Surfer',          location: 'Beach Shack',
      schedule: 'Beach all day · Bonfire nights',
      lovedGifts: ['Coconut', 'Sea Urchin', 'Palm Fruit'],
      quest: 'Organize the island surf competition. Reward: Beach area expansion.',
      color: '#d97706',
    },
    {
      id: 8, name: 'Mira',  initials: 'MI', role: 'Artist',          location: 'Studio Cove',
      schedule: 'Studio 6am–12pm · Village afternoons',
      lovedGifts: ['Sunflower', 'Amethyst', 'Sea Crystal'],
      quest: 'Creating an island mural — needs pigment materials and creative inspiration.',
      color: '#ec4899',
    },
  ],

  mineUnlocks: {
    earth:    'Available from Day 1 — no requirements.',
    water:    'Unlock at Town Rank D: donate 30 items to the island museum.',
    wind:     "Unlock at Town Rank C: complete Tidal's coral reef quest line.",
    fire:     'Unlock at Town Rank B: clear all 40 floors of the Wind Mine.',
    memories: 'Unlock at Town Rank A: triggered by a special seasonal event (secret).',
  },
};
